### PR TITLE
switched from declarative to programmatic transactions

### PR DESCRIPTION
**Pull request by fterrier**

### CODE REVIEW

**Comment by susanm74** [comment]
This doesn't look like the branch merged the most recent master into it first, as I'm not seeing some changes I just pushed. Its not a big deal, but it might be good to do beforehand to save time and resolve any conflicts and fix any tests prior to making the pull request, as the pull request should be pretty close to a clean/quick/smooth merge back into master to push.

**Comment by susanm74** [comment]
Nevertheless, +1

**Comment by fterrier** [comment]
yeah in that case I agree with you, let me do that

**Comment by susanm74** [comment]
Thx man!

On Wed, May 23, 2012 at 2:49 PM, François Terrier <
reply@reply.github.com

**Pull request merged**
