### PR TITLE
renamed help class to nav-help

### PR DESCRIPTION
**Pull request by fterrier**

### CODE REVIEW

**Comment by susanm74** [comment]
Looks good, but in grails-app/views/cost/view.gsp, should it be "Please select a location / program" not "an"? And should that use message.properties?

**Comment by fterrier** [comment]
yes it should, and it's not the only one that is not using messages.properties

i guess we should create a branch for all that messages.properties stuff that's missing?

**Comment by susanm74** [comment]
Yep, and a redmine ticket!

On Tue, Mar 13, 2012 at 11:54 AM, François Terrier <
reply@reply.github.com

**Comment by fterrier** [comment]
yesboss

**Pull request merged**
