### PR TITLE
"My Account" page and default language

### PR DESCRIPTION
**Pull request by fterrier**
- added a defaultLanguage field that the user gets redirected to upon login
- slightly modified the registration page to ask for phone number and preferred language
- added a "my account" page where one can change phone number, preferred language, first name and last name

### CODE REVIEW

**Comment by susanm74** [comment]
+1

**Comment by fterrier** [comment]
little migration script for the last commit

UPDATE User set landingPage = "PLANNING" where landingPage = "planning";
UPDATE User set landingPage = "SURVEY" where landingPage = "survey";
UPDATE User set landingPage = "OTHER" where landingPage is null;
ALTER TABLE  `User` CHANGE  `landingPage`  `userType` VARCHAR( 255 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE  `User` CHANGE  `dataLocationId`  `locationId` INT( 11 ) NULL DEFAULT NULL;
UPDATE User set organisation = location WHERE organisation is null;
UPDATE User set location = organisation WHERE location is null;
ALTER TABLE  `User` DROP  `location`;

**Comment by susanm74** [comment]
Shouldn't lowercase/uppercase be happening in CSS? ex. planning/survey/etc

Sue

On Wed, Jun 20, 2012 at 12:13 PM, François Terrier <
reply@reply.github.com

**Comment by fterrier** [comment]
This "landingPage" property has been removed from the User domain object, but I've reused the DB column and renamed it to "userType", which is an enum that indicates whether the user is a Planner, a Surveyor or an ordinary user. That enum is upper-case so I had to change the content of the column to be uppercase as well.

Check it out.

**Comment by susanm74** [comment]
Ah, enums, got it. +1

On Wed, Jun 20, 2012 at 12:19 PM, François Terrier <
reply@reply.github.com

**Comment by susanm74** [comment]
ship THAT sh*t!

**Pull request merged**
